name: ArtLover
favicon: null
layout_spectrum: 0.9495568661950529
typography_spectrum: 0.6238577491603792
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#a4a2a1'
    - '#181818'
    - '#7c7c7c'
    - '#fed5df'
    - '#373737'
  brandStrength: 0.3775377916172147
  lightness: 0.5
  saturation: 0.0625
  rhythmicContrast: 0.5
purpose: []
