name: ArtLover
favicon: null
layout_spectrum: 0.9495568661950529
typography_spectrum: 0.6238577491603792
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.3775377916172147
  lightness: 0.09089026623405516
  saturation: 0.694566534133628
  rhythmicContrast: 0.028700900496914983
purpose: []
